### ISSUE TITLE
API: __all__

### ISSUE THREAD

**Issue by hugovk** [crflynn/pypistats.org#14]
Downloads stats for all packages can be found under the special keyword `__all__`:

* https://pypistats.org/packages/__all__

However, calling the API on `__all__` returns 404:

* https://pypistats.org/api/packages/__all__/recent

Compare with a "real" package:

* https://pypistats.org/api/packages/pip/recent

Would it be possible to expose `__all__` via the API in some way?

Thank you!

**Comment by crflynn** [comment]
Looks like an earlier fix actually broke this. Should be available now.
