### ISSUE TITLE
Reverse dependency lookup: who is using my package?

### ISSUE THREAD

**Issue by itamarst** [crflynn/pypistats.org#15]
I can see which packages my package depends on. E.g. https://pypistats.org/packages/eliot shows Eliot depends on six, zope,interface, etc..

In order to track usage of my package, I'd love to be able to do the reverse lookup. I.e. be able to answer the question: which packages depend on `eliot`?

**Comment by itamarst** [comment]
Oops. To back up a bit: thank you for building this, it's very informative! And if you have no time or interest in doing the above I totally get it. But if you happen to feel like it... :grin:

**Comment by hugovk** [comment]
Libraries.io says 2 packages and 49 repos depend on Eliot:

* https://libraries.io/pypi/eliot

**Comment by itamarst** [comment]
Ah, neat. That's probably good enough.
