### ISSUE TITLE
Download stats seem too high

### ISSUE THREAD

**Issue by robotichead** [crflynn/pypistats.org#16]
**Method**

1. Go to https://pypistats.org/packages/nearbeach

**Expected Results**

Download stats to be in single digits as it is an unknown app.

**Actual Results**

Downloads a month > 100

**Notes**

On the about page - https://pypistats.org/about - there is a link to the Google Big Data but it just shows the error "Unable to find table: the-psf:pypi.downloads". Do we know what is counted as a download?

**Comment by crflynn** [comment]
The stats are less reliable for less popular packages since there are mirrors, bots, crawlers, etc that will generate downloads recorded in bigquery. To access the bigquery tables, you must have a google cloud account.
