### ISSUE TITLE
502, 504 or slow response on all requests

### ISSUE THREAD

**Issue by orsinium** [crflynn/pypistats.org#20]
Don't die, please :heart:

**Comment by crflynn** [comment]
Looks like the API is being spammed right now by someone using `python-requests`. I didn't design this application's infrastructure to scale to any degree but I'll look into what I can do to remedy this.

**Comment by hugovk** [comment]
https://github.com/hugovk/pypistats uses requests, but then requests is the [4th most downloaded package](https://hugovk.github.io/top-pypi-packages/).

Would it help to add a User-Agent?

**Comment by orsinium** [comment]
Yeah, it could be anyone. However, it's a good reminder to set User-Agent. I've made an issue in my tool as well:
https://github.com/dephell/dephell/issues/231

**Comment by hugovk** [comment]
PR to add User-Agent: https://github.com/hugovk/pypistats/pull/65.

**Comment by crflynn** [comment]
I've disabled the API for the time being. I don't have much time right now to try to resolve this but I don't want the service to be completely unusable for the community. The charts should be viewable for now at least.

**Comment by calebcartwright** [comment]
Hi there! Obviously we're big consumers of pypistats.org at Shields.io (we use `Shields.io` for user-agent) although based on the thread it doesn't sound like we're the ones causing the spam. Please let us know if we are though.

**Comment by crflynn** [comment]
While shields makes up a majority of the requests it was not what caused this issue. It was an individual who was trying to scrape the entirety of the API. 

I'll reiterate that it is basically free to get all of this information directly from BigQuery (and in only a few seconds of query time).

**Comment by bryevdv** [comment]
@crflynn it seems like the API is back on? Were there any changes or should any sort of "pile up" be expected from the down time? The Bokeh download numbers are basically double what they were a week ago, which would be great if true, of course :D but also seems worth asking about

**Comment by hugovk** [comment]
> PR to add User-Agent: [hugovk/pypistats#65](https://github.com/hugovk/pypistats/pull/65).

Merged and released in 0.7.0.
