### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by gittar** [crflynn/pypistats.org#24]
since yesterday I can not reach pypistats.org anymore. All I get is a page saying „500“. I hope it will be up again soon. Thx for the great service.

**Comment by samuelcolvin** [comment]
@crflynn anything we can do to help fix this?

I also noticed before it went down that we missed a couple of days of data at the end of december, maybe related?

**Comment by crflynn** [comment]
Should be fixed now. @samuelcolvin: Regarding the missing days I'll have to backfill those when I get the chance. Usually incomplete ingestions are due to download records that don't parse nicely. Thanks for the heads up @gittar.

**Comment by samuelcolvin** [comment]
thanks so much.

**Comment by gittar** [comment]
Excellent. Thanks.
