### ISSUE TITLE
pypistats.org has NO new data since July 19.

### ISSUE THREAD

**Issue by DanielGoldfarb** [crflynn/pypistats.org#29]
pypistats.org has NO new data since July 19.

There is also ZERO for the data for all packages on April 8th, 2020, and on July 18, 2020.  These may be related and/or due to the same cause (once that cause is discovered).

**Comment by DanielGoldfarb** [comment]
@crflynn Chris, @ mentioning you here to hopefully draw your attention.  Please let me know if there is anything I can do to help.   All the best.  --Daniel

**Comment by chris48s** [comment]
@crflynn - would it be possible to get a response to this issue?
Even if the response is "I have no time to work on this" or  "I am no longer interested in maintaining this project", that's valuable information for us at this point.
Hope all is ok.

**Comment by crflynn** [comment]
I'm going to put some focus on this starting today. I found the problem, but the state of the app and its deployment is quite poor and needs improvement. I'll just say that I'm working on fixing it. I appreciate the issue being brought up, however, so thank you.

**Comment by jewettaij** [comment]
It's never fun to get bug reports like this on an old project.  Judging by the *vast* number of github projects I see with pypi download badges, I think more people will recognize the usefulness of your work when they notice their download counts are curiously dropping.  (As I did.  I am probably too invested in these download numbers.)  Thanks for maintaining this service.

**Comment by bthate** [comment]
Any progres with fixing pypistats.org ? Getting a presistent 502 Bad Gateway, as if it has been disabled completely ? Fix would be welcomed here, it's too silent when no download stats are available .. thnx !

**Comment by psincraian** [comment]
Meanwhile you can use [pepy.tech](https://pepy.tech/) to view download stats and to get the badge 😊

**Comment by jewettaij** [comment]
> Meanwhile you can use [pepy.tech](https://pepy.tech/) to view download stats and to get the badge

Thanks Petru.  I'll take a look at this.  A service like this helps me advance my agenda to show funding agencies and potential journal editors that the software I wrote is used by people.

At first glance, I noticed that the download numbers at pepy.tech appear to be much larger than they were at pypistats.org.  Are you including downloads from mirrors?  I'll create an issue on your project page, so you don't have to reply here.  (I am also curious whether we should count downloads whose python version and OS are listed as "unknown", but you don't have to reply to this question.)

**Comment by nschloe** [comment]
@jewettaij https://github.com/psincraian/pepy/issues/224

**Comment by jewettaij** [comment]
also:
psincraian/pepy#164

**Comment by crflynn** [comment]
It's back. There is some data that still needs to be backfilled.

**Comment by piccolomo** [comment]
I guess the problem is back! Isn't it? 

Anyway thanks to maintainer of the project!

**Comment by crflynn** [comment]
i'm backfilling it right now

**Comment by piccolomo** [comment]
> i'm backfilling it right now

Thanks for quick reply, and good luck!
