### ISSUE TITLE
Do we know what explain the factor 2 in number of download since July 30 ?

### ISSUE THREAD

**Issue by jcfr** [crflynn/pypistats.org#3]
First, thanks for creating this awesome website :smile: :+1: 

Second, here are some screenshots and links to illustrate

Source: https://pypistats.org/packages/__all__

![image](https://user-images.githubusercontent.com/219043/44493246-440d4d00-a635-11e8-8d0a-9bb2986538e7.png)

Worth noting this is specific to linux downloads ... 

![image](https://user-images.githubusercontent.com/219043/44493395-cb5ac080-a635-11e8-9db1-0cd78d5a3182.png)

This trend can be observed with individual packages too:
* https://pypistats.org/packages/pip
* https://pypistats.org/packages/cmake

**Comment by crflynn** [comment]
See here: https://github.com/pypa/linehaul/issues/30

The previous iteration of linehaul was flapping and dropping a significant number of download records. You can see in that thread that the new version was deployed on July 26, which has since provided much more reliable data.

**Comment by jcfr** [comment]
Makes sense. Thanks for the explanation.

Anticipating others may have the same question, I suggest we keep the issue open for some time. But if you prefer to close it, that would also work for me.

**Comment by crflynn** [comment]
I'll keep it open for now. What I really should do is add an FAQ page.

**Comment by crflynn** [comment]
I've added an FAQs page just now, so I'm going to go ahead and close this issue.
