### ISSUE TITLE
Website is not functioning

### ISSUE THREAD

**Issue by MakufonSkifto** [crflynn/pypistats.org#40]
Whenever I go to https://pypistats.org/, I get greeted with this message: 
![image](https://user-images.githubusercontent.com/63517174/123537329-820d1280-d737-11eb-9832-b06e9b0cb175.png)
 I'm thinking that this is a problem on the websites and PyPI API's side. Please fix this as soon as possible.

**Comment by hugovk** [comment]
This is now working.

**Comment by MakufonSkifto** [comment]
Yeah It got fixed yesterday.
