### ISSUE TITLE
Intermittent 429 RATE LIMIT EXCEEDED

### ISSUE THREAD

**Issue by domdfcoding** [crflynn/pypistats.org#42]
Hi,

I am intermittently faced with a `429 RATE LIMIT EXCEEDED` error when browsing pypistats.org

I'm only browsing the odd page, not making tonnes of requests through the API, so this is a little odd. It doesn't happen all of the time; maybe 25-30% of requests succeed. I have confirmed this on a different device using a different internet connection, so I think this is an issue at your end rather than mine.

**Comment by simonw** [comment]
I just got the 429 error browsing the site homepage from my phone at home! I don't think I exceeded the rate limit - I guess it's possible I hit 30 resources within a minute if it's counting CSS and image loads too? https://github.com/crflynn/pypistats.org/blob/da4d4aa8da682047330dc8f6c5a8ea49c88e7905/pypistats/run.py#L23

**Comment by Sodium-Hydrogen** [comment]
I am seeing a 429 for all attempts from my ip address including the very first one in days. I am not able to view any pages no matter how long I wait between attempts.

**Comment by JessicaS11** [comment]
@learn2pheonix and I are having the same issues. We were trying to test a download script only to discover we can't even navigate to [https://pypistats.org/](https://pypistats.org/) without getting the error. Any idea what's going on or if a resolution is being worked on? I'd like to know if I need to switch to getting my PyPI stats another way!

**Comment by crflynn** [comment]
Lots of request spam (abuse) and a misconfigured limiter. Should be back to normal.
