### ISSUE TITLE
[Bug] Downloads stats for all packages got significant drop. 

### ISSUE THREAD

**Issue by ternaus** [crflynn/pypistats.org#67]
[url for all](https://pypistats.org/packages/__all__)

<img width="678" alt="Screenshot 2024-06-19 at 18 33 18" src="https://github.com/crflynn/pypistats.org/assets/5481618/1cfa8ae9-2695-4c68-bc24-751693e1d9f3">

@hugovk @crflynn 

Downloads for all packages, like all-all-all, show significant drop in downloands in the past two days

**Comment by ternaus** [comment]
Looks like the issue was addressed

**Comment by hugovk** [comment]
It's been fixed upstream, but this project should still backfill the missing data to fix the big dip:

![Screenshot_20240701_085037_Chrome](https://github.com/crflynn/pypistats.org/assets/1324225/87bd3880-a527-45e5-92bd-968c357c49da)

https://pypistats.org/packages/__all__
