### ISSUE TITLE
Announcing a command-line tool

### ISSUE THREAD

**Issue by hugovk** [crflynn/pypistats.org#8]
Hello, thank you very much for creating https://pypistats.org!

And thank you very much for creating an API as well, I've made a command-line tool `pypistats` that uses the API :)

https://pypi.org/project/pypistats
https://github.com/hugovk/pypistats

Here's example use:

```console
$ pypistats python_minor pillow --last-month
| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  46.64% | 1,512,429 |
|      3.6 |  30.34% |   983,838 |
|      3.5 |  12.53% |   406,429 |
|      3.7 |   6.12% |   198,558 |
|      3.4 |   3.41% |   110,552 |
| null     |   0.84% |    27,380 |
|      3.3 |   0.05% |     1,599 |
|      2.6 |   0.05% |     1,581 |
|      3.2 |   0.01% |       246 |
|      3.8 |   0.00% |       133 |
|      2.4 |   0.00% |         7 |
| Total    |         | 3,242,752 |
```

And the output is actually Markdown (though JSON is available via a switch), so can be pasted into GitHub like this:

| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  46.64% | 1,512,429 |
|      3.6 |  30.34% |   983,838 |
|      3.5 |  12.53% |   406,429 |
|      3.7 |   6.12% |   198,558 |
|      3.4 |   3.41% |   110,552 |
| null     |   0.84% |    27,380 |
|      3.3 |   0.05% |     1,599 |
|      2.6 |   0.05% |     1,581 |
|      3.2 |   0.01% |       246 |
|      3.8 |   0.00% |       133 |
|      2.4 |   0.00% |         7 |
| Total    |         | 3,242,752 |

This issue is just to let you know and to say thanks, feel free to close it once you've read it :)

**Comment by crflynn** [comment]
I just played around with it for a bit; very slick!

I'll give this project a plug on the about/api pages :)

**Comment by crflynn** [comment]
...and deployed!
